server:
  port: 8083
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xcx-estore?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xcx123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
logging:
  config: classpath:log4j2-spring.xml